connect remote:localhost/cmdb user pass

DELETE VERTEX V
DELETE EDGE E


CREATE CLASS Component IF NOT EXISTS EXTENDS V 

CREATE CLASS ExecutionEnvironment IF NOT EXISTS EXTENDS V 
CREATE CLASS Artifact IF NOT EXISTS EXTENDS V 
CREATE CLASS DeploymentSpec IF NOT EXISTS EXTENDS V 
CREATE CLASS DeviceNode IF NOT EXISTS EXTENDS V 
CREATE CLASS DeploymentSpec IF NOT EXISTS EXTENDS V 
CREATE CLASS PropertyValue IF NOT EXISTS EXTENDS V 
CREATE CLASS PropertyName IF NOT EXISTS EXTENDS V 
CREATE CLASS LogicalComponent IF NOT EXISTS EXTENDS Component 
CREATE CLASS PhysicalComponent IF NOT EXISTS EXTENDS Component 
CREATE CLASS LogicalExecutionEnvironment IF NOT EXISTS EXTENDS ExecutionEnvironment 
CREATE CLASS PhysicalExecutionEnvironment IF NOT EXISTS EXTENDS ExecutionEnvironment 
CREATE CLASS LogicalDeploymentSpec IF NOT EXISTS EXTENDS DeploymentSpec 
CREATE CLASS PhysicalDeploymentSpec IF NOT EXISTS EXTENDS DeploymentSpec

CREATE CLASS Delivery_Instance IF NOT EXISTS EXTENDS E 
CREATE CLASS Manifested_By IF NOT EXISTS EXTENDS E 
CREATE CLASS Deployed_To IF NOT EXISTS EXTENDS E 
CREATE CLASS Instance_Of IF NOT EXISTS EXTENDS E 
CREATE CLASS Has IF NOT EXISTS EXTENDS E 
CREATE CLASS Hosted_By IF NOT EXISTS EXTENDS E 

CREATE CLASS DatabaseConnection IF NOT EXISTS EXTENDS V 
CREATE CLASS Connects_To IF NOT EXISTS EXTENDS E 




