connect remote:localhost/cmdb user pass

CREATE CLASS Component IF NOT EXISTS EXTENDS V 
CREATE CLASS ExecutionEnvironment IF NOT EXISTS EXTENDS V 
CREATE CLASS Artifact IF NOT EXISTS EXTENDS V 
CREATE CLASS DeploymentSpec IF NOT EXISTS EXTENDS V 
CREATE CLASS DeviceNode IF NOT EXISTS EXTENDS V 
CREATE CLASS DeploymentSpec IF NOT EXISTS EXTENDS V 
CREATE CLASS PropertyValue IF NOT EXISTS EXTENDS V 
CREATE CLASS PropertyName IF NOT EXISTS EXTENDS V 

CREATE VERTEX Component SET key = "IRS"
CREATE VERTEX Component SET key = "DELIVERY_IRS"
CREATE VERTEX  Artifact SET key = "IRS_EAR"
CREATE VERTEX  ExecutionEnvironment SET key = "WLH01"
CREATE VERTEX  ExecutionEnvironment SET key = "DELIVERY_WLH01"
CREATE VERTEX  DeploymentSpec SET key = "DELIVERY_IRS_DEPLOYMENTSPEC"
CREATE VERTEX  DeploymentSpec SET key = "IRS_DEPLOYMENTSPEC"
CREATE VERTEX DeviceNode SET key = "BLEWIT"

CREATE CLASS Delivery_Instance IF NOT EXISTS EXTENDS E 
CREATE CLASS Manifested_By IF NOT EXISTS EXTENDS E 
CREATE CLASS Deployed_To IF NOT EXISTS EXTENDS E 
CREATE CLASS Instance_Of IF NOT EXISTS EXTENDS E 
CREATE CLASS Has IF NOT EXISTS EXTENDS E 
CREATE CLASS Hosted_By IF NOT EXISTS EXTENDS E 

CREATE EDGE Delivery_Instance FROM (SELECT FROM COMPONENT WHERE key = "IRS") TO (SELECT FROM COMPONENT WHERE key = "DELIVERY_IRS")

CREATE EDGE Manifested_By FROM (SELECT FROM COMPONENT WHERE key = "IRS") TO (SELECT FROM Artifact WHERE key = "IRS_EAR")

CREATE EDGE Deployed_To FROM (SELECT FROM Artifact WHERE key = "IRS_EAR") TO (SELECT FROM ExecutionEnvironment WHERE key = "WLH01")

CREATE EDGE Deployed_To FROM (SELECT FROM COMPONENT WHERE key = "DELIVERY_IRS") TO (SELECT FROM ExecutionEnvironment WHERE key = "DELIVERY_WLH01")

CREATE EDGE Instance_Of FROM (SELECT FROM ExecutionEnvironment WHERE key = "WLH01") TO (SELECT FROM ExecutionEnvironment WHERE key = "DELIVERY_WLH01")

CREATE EDGE Has FROM (SELECT FROM COMPONENT WHERE key = "DELIVERY_IRS") TO (Select FROM DeploymentSpec WHERE key = "DELIVERY_IRS_DEPLOYMENTSPEC")

CREATE EDGE Instance_Of FROM (Select FROM DeploymentSpec WHERE key = "IRS_DEPLOYMENTSPEC") TO (Select FROM DeploymentSpec WHERE key = "DELIVERY_IRS_DEPLOYMENTSPEC")

CREATE EDGE Deployed_To FROM (Select FROM Artifact WHERE key = "IRS_EAR") TO (Select FROM DeploymentSpec WHERE key = "IRS_DEPLOYMENTSPEC")

CREATE EDGE Hosted_By FROM (SELECT FROM ExecutionEnvironment WHERE key = "DELIVERY_WLH01") TO (SELECT FROM DeviceNode WHERE key = "BLEWIT")




